server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/level_up?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1290
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
auth:
  url:
    auht-micro: http://localhost:8001/api/v1/authentication/token/verify
    url-verify: http://localhost:5173/
carrito:
  url:
    get-id: http://localhost:8003/api/carrito/{id}
    vaciar: http://localhost:8003/api/carrito/{id}/vaciar